#!/bin/sh
#
export EDITOR=/usr/bin/nvim
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export PATH="$HOME/Scripts:$HOME/.local/bin:$HOME/node_modules/.bin:$HOME/Documents/flutter/bin:$HOME/go/bin:$PATH"

udiskie &
syncthing --no-browser &
